# Generated by Django 5.0.7 on 2024-08-03 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'managed': True, 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'managed': True, 'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqa'},
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='update_time',
            new_name='updeted_time',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='body',
            field=models.TextField(verbose_name='Yangilik haqida malumotlar'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel', verbose_name='Kategoriyasiz'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news/image', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yangilik yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='status',
            field=models.CharField(choices=[('Faol emas', 'Faol emas'), ('Faol', 'Faol')], default='Faol emas', max_length=50, verbose_name='Holati'),
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='Kategoriya',
        ),
    ]
